name: dart_sunvox
description: Dart FFI binding for libsunvox
version: 0.0.4
homepage: https://github.com/maks/dart_sunvox

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  path: ^1.8.0
  ffi: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  ffigen: ^6.1.2
  

ffigen:
  name: "libsunvox"
  output: "lib/src/libsunvox_generated_bindings.dart"
  headers:
    entry-points:
      - "sunvox_static.h"
  llvm-path:
    - "/usr/lib/llvm-13"
  structs:
    rename:
      "_(.*)": "$1_"
    member-rename:
      ".*":
        "_(.*)": "$1_"
