// obtained from https://github.com/metrasynth/radiant-voices/search?q=readonly+typeName+%3D
const Set<String> allModuleTypes = {
  "ADSR",
  "Amplifier",
  "Analog generator",
  "Compressor",
  "Ctl2Note",
  "DC Blocker",
  "Delay",
  "Distortion",
  "DrumSynth",
  "Echo",
  "EQ",
  "Feedback",
  "Flanger",
  "Glide",
  "GPIO",
  "Generator",
  "Sound2Ctl",
  "Input",
  "LFO",
  "Kicker",
  "Loop",
  "MultiCtl",
  "Modulator",
  "Output",
  "Pitch2Ctl",
  "Pitch shifter",
  "Reverb",
  "Velocity2Ctl",
  "Vibrato",
  "WaveShaper",
  "Vorbis player",
  "Vocal filter",
  "MetaModule",
  "SpectraVoice",
  "Sampler",
  "Pitch Detector",
  "Filter",
  "FM",
  "Filter Pro",
  "MultiSynth",
};

const instrumentTypesList = [
  "Analog Generator",
  "DrumSynth",
  "FM",
  "FMX",
  "Generator",
  "Kicker",
  "MetaModule",
  "MultiSynth",
  "Sampler",
  "SpectraVoice",
  "Vorbis player",
];
